### PR TITLE
Cosmwasm plus compatibility

### LINKED ISSUE #18: Adapt rust optimizer for cosmwasm-plus
We currently support two modes:

* The simple mode is when the repo has exactly one contract in it, no arguments provided.
* The multi-repo mode was designed for `cosmwasm-examples`, where each contract is *not* in the workspace

However, it fails when we try to build `cosmwasm-plus`:

* Multi-repo with all contracts in the same workspace (needed as we import from other packages)

There are two key differences here that cause the build error:

1. (Stack trace below) target where the code goes is not in the directory with the contract's Cargo.toml, but in the repo root
2. (May cause an issue) multiple contracts will all compile to the same target dir. This means `*.wasm` will not be unique, but we need the name of the contract we compile.

------

Output of a failed build (see bottom):

```
$ docker run --rm -v "$(pwd)":/code \
>   --mount type=volume,source="cosmwasm_plus_cache",target=/code/target \
>   --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
>   cosmwasm/rust-optimizer:0.9.0 ./contracts/cw1-subkeys
Building contract in /code/contracts/cw1-subkeys
    Updating crates.io index
 Downloading crates ...
   ....
   Compiling cw20 v0.1.0 (/code/packages/cw20)
   Compiling cw1-whitelist v0.1.0 (/code/contracts/cw1-whitelist)
   Compiling cw1-subkeys v0.1.0 (/code/contracts/cw1-subkeys)
    Finished release [optimized] target(s) in 1m 08s
Failed opening 'target/wasm32-unknown-unknown/release/*.wasm'
```

That failed as it looked for `/code/contracts/cw1-subkeys/target` not `/code/target`

### PR DESCRIPTION
**Pull request by ethanfrey**
Closes #18 
Required for https://github.com/CosmWasm/cosmwasm-plus/pull/29

This adds a second script that handles the `cosmwasm-plus` case nicely, while leaving the `optimize.sh` script untouched.

The one issue that changes in the external API is that we cannot use entrypoint anymore. The default (no argument) compile works as is, but the `cosmwasm` compile process now requires `optimize.sh ./contracts/hackatom` at the end.

Updated the README to explain these cases.

### CODE REVIEW

File: optimize.sh [hunk 1]
```diff
@@ -4,6 +4,13 @@ command -v shellcheck > /dev/null && shellcheck "$0"
 
 export PATH=$PATH:/root/.cargo/bin
 
+# There are three cases here
+# 1. Repo contains only one contract, mounted at root: `./optimize.sh` (eg. `cosmwasm-template`)
+# 2. Repo contains multiple contracts, not in one workspace. We mount docker at root and pass
+#    the path to the contract: `./contracts/erc20` (eg. `cosmwasm-examples`)
+# 3. Repo contrains multiple contracts, all in one workspace. (eg. `cosmwasm-plus`)
```
Comment (maurolacy) [inline optimize.sh:11]: <nit> `s/contrains/contains/`

File: multi-optimize.sh [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+  name=$(basename "$wasm")
+  wasm-opt -Os "$wasm" -o "artifacts/$name"
+done
+
+(
+  cd artifacts
+  sha256sum -- *.wasm > hash.txt
+)
+
+echo "done"
```
Comment (maurolacy) [inline multi-optimize.sh:38]: This looks OK, but I think a version that does the "single" vs. "multi" stuff automatically would be nice.

**Comment by ethanfrey** [comment]
Interesting point Simon.

I tried `cargo build --release --target wasm32-unknown-unknown` on the repo root and it generated all contract wasm (even faster than once per dir) and didn't include the non-contract packages.

It doesn't even require any arguments there. I will update and talk tomorrow.
Good night

**Comment by maurolacy** [comment]
> Interesting point Simon.
> 
> I tried `cargo build --release --target wasm32-unknown-unknown` on the repo root and it generated all contract wasm (even faster than once per dir) and didn't include the non-contract packages.
> 
> It doesn't even require any arguments there. I will update and talk tomorrow.
> Good night

Yes, but what about non-workspace contracts?

**Comment by webmaster128** [comment]
The other issue I see with this (and any multi-target build system in general) is how source code verification can work. If we don't get verification, we don't need rust-optimizer, so those go hand in hand.

The following conventions would not be followed with the current approach:

> The builder is a docker image that works out of the box with docker run <builder>.
> The builder takes a volume mounted at /code which is the root of the code to be built.
> The builder must create a contract.wasm in the current directory.

https://github.com/CosmWasm/cosmwasm-verify#the-builder

The reason for those is that we need to be able to verify without project specific meta information: https://github.com/CosmWasm/cosmwasm-verify/blob/master/src/main.sh#L67-L73

This then leads us to the question what the source code archive of a cosmwasm-plus contract contains.

**Comment by ethanfrey** [comment]
> The builder is a docker image that works out of the box with docker run .
> The builder takes a volume mounted at /code which is the root of the code to be built.
> The builder must create a contract.wasm in the current directory.

Okay, this doesn't work for cosmwasm contracts right now either. But let's revisit it. How about we change it to the following (this is a 0.9 -> 0.10 so we can break stuff):

* The builder is a docker image that works out of the box with docker run (removed `.`)
* The builder takes a volume mounted at /code which is the root of the repo/workspace to be built.
* The builder must create one or more `*.wasm` files in a directory called `artifacts` and a `contracts.txt` with their respective hashes
* The `*.wasm` files must be named according to the crates that were compiled

With this, the verification steps are:

* Download the source code and uncompress it
* Run the docker container, mounting the source code under `/code`
* Check if a line in `contracts.txt` matches the desired hash -> grab the name of the contract
* (optional) validate the `sha256sum` of the named contract is correct
* find crate with the given name inside the code directory -> and return this source/schema

If this is not desired to change, then I can change the multi-optimizer.sh to have the same output as optimizer does (but then it takes a subpath.... not according to spec either). 

In either case, I should do some workspace-detection tricks, so we don't need arguments in the validator

**Comment by webmaster128** [comment]
> this doesn't work for cosmwasm contracts right now either.

Right, this is why I call them "development contracts" whenever I can to express those must not be taken seriously. There is no concept for source publication for them either.

**Comment by webmaster128** [comment]
The proposed rules are good. Some additional comments:

- There is no dot in the `docker run` call. This was the end of the sentence and the `<builder>` valiable got lost. Bottom line: don't use html tags as placeholder in markdown. See point 1 in https://github.com/CosmWasm/cosmwasm-verify#the-builder. So this point can remain unchanged.
- Do we need a separate builder for the monorepo then?
- _The *.wasm files must be named according to the crates that were compiled_ I'm a fan of this and we tried that before: https://github.com/CosmWasm/rust-optimizer/pull/8

**Comment by ethanfrey** [comment]
Okay, I would agree with these changes. I would try to make mono-repo and single-contract run in the same builder. (and say we don't support cosmwasm builds except with additional arguments, but violating the verifier approach).

This means, I can make a default CMD that only supports `cosmwasm-template` and `cosmwasm-examples` (rooted in one crate) or `cosmwasm-plus` (rooted in repo root) style and not `cosmwasm` style. The `cosmwasm` style could be a non-default script and require arguments. Do I understand this properly?

I think I can unify these use cases as long as `cosmwasm` support is separate.

I will make all scripts return a set in `artifacts` along with names.

**Comment by webmaster128** [comment]
> This means, I can make a default CMD that only supports `cosmwasm-template` and `cosmwasm-examples` (rooted in one crate) or `cosmwasm-plus` (rooted in repo root) style and not `cosmwasm` style. The `cosmwasm` style could be a non-default script and require arguments. Do I understand this properly?

Yes, perfect. Whatever we do in the cosmwasm repo is for VM maintainers only (relative paths to vm and std) and should never be deployed to any serious chain.

**Comment by ethanfrey** [comment]
Okay @webmaster128 please check out the latest commit (or just check the README usage).

I tested this manually on `cosmwasm-examples` (mounting the `erc20` package as root), `cosmwasm-plus` (mounting repo root), and `cosmwasm` (using a non-standard argument `./contracts/burner`).

All have the same behavior of placing named wasm files inside `artifacts` along with a `contracts.txt` file. Given this is how we publish them (also in cosmwasm) and not committing wasm to the source repo, this seems like a nicer standard approach that works for all cases.

File: Dockerfile [hunk 3]
```diff
@@ -15,9 +15,9 @@ COPY --from=0 /emsdk_portable/binaryen/bin/wasm-opt /usr/local/bin
 WORKDIR /code
 
 # Add out script as entry point
-ADD optimize.sh /opt/optimize.sh
-RUN chmod +x /opt/optimize.sh
+ADD optimize.sh /usr/local/bin/optimize.sh
+RUN chmod +x /usr/local/bin/*.sh
```
Comment (webmaster128) [inline Dockerfile:19]: I'd just change the files we copied there to avoid surprises. However, it should be correct both ways.

File: README.md [hunk 4]
```diff
@@ -21,13 +24,43 @@ you to produce a smaller build that works with the cosmwasm integration tests
...
+
+```shell
+docker run --rm -v "$(pwd)":/code \
+  --mount type=volume,source="devcontract_cache_burner",target=/code/contracts/burner/target \
+  --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
+  cosmwasm/rust-optimizer:0.10.0 ./contracts/burner
+
+ls -l ./artifacts/*.wasm
+cat ./artifacts/contracts.txt
+```
```
Comment (webmaster128) [inline README.md:62]: We never documented this use case before and might even remove this feature from here if scripts get too complicated. I'd remove the entire block to keep it simple for users.

File: optimize.sh [hunk 5]
```diff
@@ -4,20 +4,45 @@ command -v shellcheck > /dev/null && shellcheck "$0"
 
 export PATH=$PATH:/root/.cargo/bin
 
-# This parameter allows us to mount a folder into docker container's "/code"
-# and build "/code/contracts/mycontract".
-contractdir="$1"
-echo "Building contract in $(realpath -m "$contractdir")"
+mkdir -p artifacts
+contractdir=${1:-.}
```
Comment (webmaster128) [inline optimize.sh:8]: With the Dockerfile in this PR, $1 is always set, right? Then we can avoid defining the default value in two places

File: optimize.sh [hunk 6]
```diff
@@ -4,20 +4,45 @@ command -v shellcheck > /dev/null && shellcheck "$0"
...
+  # and build "/code/contracts/mycontract".
+  echo "Building contract in $(realpath -m "$contractdir")"
+  (
+    cd "$contractdir"
+
+    # Linker flag "-s" for stripping (https://github.com/rust-lang/cargo/issues/3483#issuecomment-431209957)
+    # Note that shortcuts from .cargo/config are not available in source code packages from crates.io
+    RUSTFLAGS='-C link-arg=-s' cargo build --release --target wasm32-unknown-unknown --locked
+  )
+fi
```
Comment (webmaster128) [inline optimize.sh:30]: I think we don't need the `if` and duplication of the build command since `cd .` works in the first case as well. A text like `echo "Building all contracts in $(realpath -m "$contractdir")"` works for all cases.

File: optimize.sh [hunk 7]
```diff
@@ -4,20 +4,45 @@ command -v shellcheck > /dev/null && shellcheck "$0"
...
+for wasm in "$contractdir"/target/wasm32-unknown-unknown/release/*.wasm; do
+  name=$(basename "$wasm")
+  echo "Optimizing $name"
+  wasm-opt -Os "$wasm" -o "artifacts/$name"
+done
+
+# create hash
+(
+  cd artifacts
+  sha256sum -- *.wasm > contracts.txt
```
Comment (webmaster128) [inline optimize.sh:42]: Is this `--` needed for something? Looks confusing to me

File: optimize.sh [hunk 8]
```diff
@@ -4,20 +4,45 @@ command -v shellcheck > /dev/null && shellcheck "$0"
...
 )
 
 echo "done"
+
+
+echo "done"
```
Comment (webmaster128) [inline optimize.sh:48]: 2x "done"?

File: optimize.sh (hunk 5 above)
Comment (ethanfrey) [reply optimize.sh:8]: Sure, I guess you are right

File: optimize.sh (hunk 7 above)
Comment (ethanfrey) [reply optimize.sh:42]: shellcheck requested it. 

If I had a file `--some-bad-thing.wasm` it would be interpreted as a flag to `sha256sum` not a file.

Not going to happen, but I just wanted shellcheck to let me run it.

File: optimize.sh (hunk 8 above)
Comment (ethanfrey) [reply optimize.sh:48]: Oops. Cut and paste.

File: optimize.sh (hunk 5 above)
Comment (webmaster128) [reply optimize.sh:8]: We can also leave the default value here and allow calling optimize.sh  with no arg. We just should decide where the default is defined.

File: optimize.sh (hunk 6 above)
Comment (ethanfrey) [reply optimize.sh:30]: I will revisit. I needed it earlier, then kept refactoring the code to minimize the if. Maybe I don't need it at all... Good eye

File: optimize.sh (hunk 7 above)
Comment (webmaster128) [reply optimize.sh:42]: Right it is, thanks for checking

🙏 holy shellcheck
